In [1]:
import numpy as np 
import pandas as pd 

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv("50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/1000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21       78.0           154.0            300.0   111.0
37       44.0            51.0            197.0    90.0
2       153.0           101.0            408.0   191.0
14      120.0           157.0            257.0   133.0
44       22.0           155.0             28.0    65.0

In [3]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21       78.0           154.0            300.0
37       44.0            51.0            197.0
2       153.0           101.0            408.0
14      120.0           157.0            257.0
44       22.0           155.0             28.0

In [4]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16908\766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16908\766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16908\766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [5]:
df.head()

    R&D Spend  Administration  Marketing Spend
21       78.0           154.0            300.0
37        NaN            51.0            197.0
2       153.0           101.0            408.0
14      120.0             NaN            257.0
44       22.0           155.0              NaN

In [6]:
# Step 1: Fill all the NaN values with mean of respective cols
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [7]:
# 0th iteration 
df0

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37      93.25           51.00            197.0
2      153.00          101.00            408.0
14     120.00          115.25            257.0
44      22.00          155.00            290.5

In [8]:
# Step 2: Remove all col1 missing values
df1 = df0.copy()

df1.iloc[1,0] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21       78.0          154.00            300.0
37        NaN           51.00            197.0
2       153.0          101.00            408.0
14      120.0          115.25            257.0
44       22.0          155.00            290.5

In [9]:
# Step 3: Predict the missing values of col1 using other cols 
X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21          154.00            300.0
2           101.00            408.0
14          115.25            257.0
44          155.00            290.5

In [10]:
y = df1.iloc[[0,2,3,4],0]
y

21     78.0
2     153.0
14    120.0
44     22.0
Name: R&D Spend, dtype: float64

In [11]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([230.50836125])

In [12]:
df1.iloc[1,0] = 230.51

In [13]:
df1

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37     230.51           51.00            197.0
2      153.00          101.00            408.0
14     120.00          115.25            257.0
44      22.00          155.00            290.5

In [14]:
# Step 4: Remove all col2 missing values
df1.iloc[3,1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21      78.00           154.0            300.0
37     230.51            51.0            197.0
2      153.00           101.0            408.0
14     120.00             NaN            257.0
44      22.00           155.0            290.5

In [15]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21      78.00            300.0
37     230.51            197.0
2      153.00            408.0
44      22.00            290.5

In [16]:
y = df1.iloc[[0,1,2,4],1]
y

21    154.0
37     51.0
2     101.0
44    155.0
Name: Administration, dtype: float64

In [17]:
lr  = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([113.55767993])

In [18]:
df1.iloc[3,1] = 113.55
df1

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37     230.51           51.00            197.0
2      153.00          101.00            408.0
14     120.00          113.55            257.0
44      22.00          155.00            290.5

In [20]:
# Remove the col3 imputed value
df1.iloc[-1,-1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37     230.51           51.00            197.0
2      153.00          101.00            408.0
14     120.00          113.55            257.0
44      22.00          155.00              NaN

In [22]:
X = df1.iloc[[0,1,2,3],[0,1]]
X

    R&D Spend  Administration
21      78.00          154.00
37     230.51           51.00
2      153.00          101.00
14     120.00          113.55

In [23]:
y = df1.iloc[[0,1,2,3],-1]
y

21    300.0
37    197.0
2     408.0
14    257.0
Name: Marketing Spend, dtype: float64

In [26]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df.iloc[4,0:2].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([264.16062123])

In [27]:
df1.iloc[-1,-1] = 264.16
df1

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00           300.00
37     230.51           51.00           197.00
2      153.00          101.00           408.00
14     120.00          113.55           257.00
44      22.00          155.00           264.16

In [28]:
df1 - df0

    R&D Spend  Administration  Marketing Spend
21       0.00             0.0             0.00
37     137.26             0.0             0.00
2        0.00             0.0             0.00
14       0.00            -1.7             0.00
44       0.00             0.0           -26.34

In [29]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2

    R&D Spend  Administration  Marketing Spend
21       78.0          154.00           300.00
37        NaN           51.00           197.00
2       153.0          101.00           408.00
14      120.0          113.55           257.00
44       22.0          155.00           264.16

In [32]:
X = df2.iloc[[0,2,3,4],1:]
X

    Administration  Marketing Spend
21          154.00           300.00
2           101.00           408.00
14          113.55           257.00
44          155.00           264.16

In [33]:
y = df.iloc[[0,2,3,4],0]
y

21     78.0
2     153.0
14    120.0
44     22.0
Name: R&D Spend, dtype: float64

In [35]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df.iloc[1,1:].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([205.6206815])

In [36]:
df2.iloc[1,0] = 205.62
df2

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00           300.00
37     205.62           51.00           197.00
2      153.00          101.00           408.00
14     120.00          113.55           257.00
44      22.00          155.00           264.16

In [37]:
df2.iloc[3,1] = np.nan 
df2

    R&D Spend  Administration  Marketing Spend
21      78.00           154.0           300.00
37     205.62            51.0           197.00
2      153.00           101.0           408.00
14     120.00             NaN           257.00
44      22.00           155.0           264.16

In [39]:
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

In [40]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([108.30994867])

In [41]:
df2.iloc[3,1] = 108.31
df2

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00           300.00
37     205.62           51.00           197.00
2      153.00          101.00           408.00
14     120.00          108.31           257.00
44      22.00          155.00           264.16

In [42]:
df2.iloc[-1,-1] = np.nan 
df2

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37     205.62           51.00            197.0
2      153.00          101.00            408.0
14     120.00          108.31            257.0
44      22.00          155.00              NaN

In [44]:
X = df2.iloc[0:4,:2]
y = df2.iloc[0:4,2]
y

21    300.0
37    197.0
2     408.0
14    257.0
Name: Marketing Spend, dtype: float64

In [46]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([37.13340366])

In [47]:
df2.iloc[-1,-1] = 37.13
df2

    R&D Spend  Administration  Marketing Spend
21      78.00          154.00           300.00
37     205.62           51.00           197.00
2      153.00          101.00           408.00
14     120.00          108.31           257.00
44      22.00          155.00            37.13

In [48]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37     -24.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -5.24             0.00
44       0.00            0.00          -227.03